name: Run cfst.py

on:
  # schedule:
  #   - cron: '0 */12 * * *'
  #   timezone: Asia/Shanghai
  workflow_dispatch:
    inputs:
      ip_type:
        description: 'IP 类型 (ipv4, ipv6, proxy)'
        required: true
        default: 'ipv4'
        type: choice
        options:
          - ipv4
          - ipv6
          - proxy

jobs:
  run-autoddns:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up environment variables
      run: |
        touch .env
        echo "API_ID=${{ secrets.API_ID }}" >> .env
        echo "API_HASH=${{ secrets.API_HASH }}" >> .env
        echo "SESSION_NAME=${{ secrets.SESSION_NAME }}" >> .env
        echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
        echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env
        echo "CLOUDFLARE_API_KEY=${{ secrets.CLOUDFLARE_API_KEY }}" >> .env
        echo "CLOUDFLARE_EMAIL=${{ secrets.CLOUDFLARE_EMAIL }}" >> .env
        echo "CLOUDFLARE_ZONE_ID=${{ secrets.CLOUDFLARE_ZONE_ID }}" >> .env
        echo "CF_WORKER_URL=${{ secrets.CF_WORKER_URL }}" >> .env
        echo "SECRET_TOKEN=${{ secrets.SECRET_TOKEN }}" >> .env
        echo "CF_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }}" >> .env
        echo "CF_KV_NAMESPACE_ID=${{ secrets.CF_KV_NAMESPACE_ID }}" >> .env
        echo "CF_API_TOKEN=${{ secrets.CF_API_TOKEN }}" >> .env

    - name: Run cfst script based on ip_type
      run: |
        python cfst.py -t ${{ github.event.inputs.ip_type }}

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        if git diff --quiet; then
          echo "No changes to commit."
        else
          git add .
          git commit -m "Auto-Update ${{ github.event.inputs.ip_type }} speed results - $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
        fi